apiVersion: v1
kind: Pod
metadata:
  name: teleport-sidepod
  namespace: teleport
spec:
  serviceAccountName: teleport-sidepod
  containers:
    - name: teleport-sidepod
      image: alirezarpi/teleport-sidepod:latest
      command: ["/trc/trc.sh"]
