apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: teleport-sidepod-rolebinding
  namespace: teleport
subjects:
  - kind: ServiceAccount
    name: teleport-sidepod
roleRef:
  kind: Role
  name: teleport-sidepod-role
  apiGroup: rbac.authorization.k8s.io
