apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: teleport-sidepod-role
  namespace: teleport
rules:
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - exec
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
